# Generated by Django 3.0.7 on 2020-06-30 06:20

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreApprovedSales",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", localflavor.br.models.BRCPFField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredSale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("date", models.DateField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Em validação"), (1, "Aprovado")], default=0
                    ),
                ),
                (
                    "cashback_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "percentage_applied",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
            ],
            options={"ordering": ["date"],},
        ),
    ]
